#+TITLE: howdy

An Emacs utility to help you keep in touch with people.

Copyright (C) 2015 Puneeth Chaganti
  - Author: Puneeth Chaganti <punchagan@muse-amuse.in>
  - Created: 24 May 2015
  - Keywords: contacts, org-mode, org-contacts
  - Homepage: http://github.com/punchagan/howdy

This file is NOT part of GNU Emacs.

Licensed under the [[http://www.gnu.org/licenses/][GPL version 3]] or later.
-----

* Commentary

Howdy! is a library to help you keep in touch with people.

You can use it to keep track of when you last contacted someone, and to
remind you to contact them again after a certain interval. It can also help
you generate an agenda view of people you need to contact.

To use Howdy!, you need to have a contacts database that is managed by
~org-contacts~.

You can configure the frequency at which you wish to contact a person by
adding a ~HOWDY_INTERVAL~ property to your contacts.

You can use the ~howdy~ function to mark a contact as contacted,
interactively. This will update the ~LAST_HOWDY~ property with the current
date. You can use the ~howdy-contacted~ function to mark a contact as
contacted, programatically. For example, look at the hooks provided in the
various integrations like ~howdy-jabber~, ~howdy-email~, ~howdy-wa~, etc.

Howdy can display a list of contacts that you need to contact, in an agenda
view. To enable this, add an entry like the one below to one of your
org-contacts-files.

: * Keep in touch
: %%(howdy-howdy)

You can also use the ~howdy-agenda-contacted~ function to mark a contact as
contacted from an org agenda buffer. You can bind this function to a
keybinding in the ~org-agenda-mode-map~ to make it easy to mark a contact as
contacted from an Org agenda.



README.org generated from the library header in ~howdy.el~ by [[https://github.com/punchagan/h2o][h2o]]
